name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: misspell
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          pattern: "*.md"
