name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: misspell
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          pattern: "*.md"
